### ISSUE TITLE
Training parameter problem when train on kitti

### ISSUE THREAD

**Issue by MiaoJieF** [drinkingcoder/FlowFormer-Official#10]
Why use an image size of [432, 960] when training on kitti? The original image height of kitti is only 375.

**Comment by drinkingcoder** [comment]
Good question! We are now re-training a model with a smaller image size for kitti. We believe the results can be tuned better:grin:.

**Comment by MiaoJieF** [comment]
Do you have any new results?

**Comment by drinkingcoder** [comment]
We have tried various image size, but, unfortunately, there is little performance variation.
