### ISSUE TITLE
About generalization results in Table 1 and Table 3 

### ISSUE THREAD

**Issue by hyBlue** [drinkingcoder/FlowFormer-Official#11]
Hi, thank you for the inspiring work!
I have a question about the results on generalization performance in Table 1 and Table 3.

In Table 1,
![image](https://user-images.githubusercontent.com/30494126/187805452-6d53da39-d199-40bb-b7aa-3ad5de1f9f71.png)

In Table 3,
![image](https://user-images.githubusercontent.com/30494126/187805501-410a9b1c-9cf7-4526-a113-4fdc94502045.png)

What is the difference between those two results on Sintel even though the results on KITTI are same?

**Comment by drinkingcoder** [comment]
The size of images in KITTI-15 is quite different from normal images. We train another model _FlowFormer#_ and use the tile technique for flow estimation on KITTI. This is explained in the [supplementary](https://drinkingcoder.github.io/publication/flowformer/images/FlowFormer-supp.pdf). The ablation study in Table 3 is also conducted with _FlowFormer#_  and tile for consistency.

Using tile in Sintel will impact the performance, i.e., 0.95/2.35, on Sintel training set as displayed [here](https://github.com/drinkingcoder/FlowFormer-Official/issues/8#issuecomment-1225235835), but is still much better than GMA.
