### ISSUE TITLE
Question about train on Flyingthing3D

### ISSUE THREAD

**Issue by MiaoJieF** [drinkingcoder/FlowFormer-Official#13]
Your work is excellent!
I have been troubled by a problem for a long time and hope to be able to get your help. When training on Flyingthings3D, the test epe of sintel and kitti fluctuates greatly. Is this normal?

**Comment by drinkingcoder** [comment]
Can you provide more information? I believe the fluctuation is abnormal. A typical curve should be like [this one](https://github.com/drinkingcoder/FlowFormer-Official/issues/8#issue-1345393108).

**Comment by MiaoJieF** [comment]
> Can you provide more information? I believe the fluctuation is abnormal. A typical curve should be like [this one](https://github.com/drinkingcoder/FlowFormer-Official/issues/8#issue-1345393108).

![image](https://user-images.githubusercontent.com/52901086/188107063-54ae1e8b-f96a-4e2f-b3a3-2f541dc6214f.png)
![image](https://user-images.githubusercontent.com/52901086/188107149-e7deac6d-efae-4ae0-a08d-d6001b532e02.png)
This is the graph when I train raft, the blue one is the training curve on Flyingthings, and the orange one is the training curve on Flyingchairs. What I want to ask is why the epe fluctuates so much when training on Flyingthings. Also, is the curve tested on sintel clean normal?

**Comment by drinkingcoder** [comment]
Do you mean you get trouble when training RAFT instead of FlowFormer?

**Comment by MiaoJieF** [comment]
> Do you mean you get trouble when training RAFT instead of FlowFormer?

Yes. The curves of Flowformer and RAFT trained on Flyingthings are similar.

**Comment by drinkingcoder** [comment]
Yes. This curve seems reasonable. You can observe that the test epe on the Sintel Clean approaches the number reported by RAFT.

**Comment by MiaoJieF** [comment]
OK. Thank you very much.
