### ISSUE TITLE
How to register a sintel account？

### ISSUE THREAD

**Issue by AMiaoJF** [drinkingcoder/FlowFormer-Official#16]
I know this question is ridiculous. I have tried all kinds of methods, but still no registration is successful. I tried to sign up with school email and google email, but it didn't work. The following information will pop up. I have also sent an email to sintel@tue.mpg.de, but have never received a reply. How did you sign up for a sintel account?
<img width="1088" alt="ef8bbae616ab13902bb098d31a03a7b" src="https://user-images.githubusercontent.com/113485477/190037200-e62190bb-e4e7-4d65-a3ae-41441b569e93.png">

**Comment by mansang127** [comment]
> I know this question is ridiculous. I have tried all kinds of methods, but still no registration is successful. I tried to sign up with school email and google email, but it didn't work. The following information will pop up. I have also sent an email to [sintel@tue.mpg.de](mailto:sintel@tue.mpg.de), but have never received a reply. How did you sign up for a sintel account? <img alt="ef8bbae616ab13902bb098d31a03a7b" width="1088" src="https://user-images.githubusercontent.com/113485477/190037200-e62190bb-e4e7-4d65-a3ae-41441b569e93.png">

I had the same problem and received an official reply email about two weeks later asking you for more detailed information.

**Comment by drinkingcoder** [comment]
I think maybe they went on vacation :rofl:. Sometimes they respond quickly but sometimes they may reply you about a week later. I also encounter they same problem at the begining.
