### ISSUE TITLE
Question about parameters printed during training

### ISSUE THREAD

**Issue by Jiafei127** [drinkingcoder/FlowFormer-Official#17]
General Thunder XP Hello! I absolutely like this task of yours, so I'd like to figure out some training parameter issues.
For example: first print round" | INFO | core.utils.logger:_print_training_status:19 - [ 100, [2.3958680439853386e-07]] 0.5127, 0.0426, 0.5117, 0.2746, 0.5180, 0.5117, 5.2532, "
What does 2.39.... in [] here mean? And I saw that there are four parameters epe, 1px, 3px, and 5px in the code, which one in the example represents? Then there are three more parameters and it is not clear what it means.
Sorry for my lack of foundation. Hope the author has time to answer it.

**Comment by drinkingcoder** [comment]
See [here](https://github.com/drinkingcoder/FlowFormer-Official/blob/02891c14118aa79672af970e205a5da74c3a410c/core/utils/logger.py#L15). We regularly print training status here. This is the learning rate.

**Comment by Jiafei127** [comment]
Well I didn't notice that, so _"0.5127, 0.0426, 0.5117, 0.2746, 0.5180, 0.5117, 5.2532,"_ correspond to _epe, 1px, 3px, 5px, th-5px_ respectively? The problem is that there are two parameters I can't find.

**Comment by drinkingcoder** [comment]
Actually, we focus on the tensorboard when checking the training details. There are also other metrics pushed into the logger [here](https://github.com/drinkingcoder/FlowFormer-Official/blob/02891c14118aa79672af970e205a5da74c3a410c/train_FlowFormer.py#L117) . Could you check details in the tensorboard?
