### ISSUE TITLE
Question about keep my own image size

### ISSUE THREAD

**Issue by youyoubud** [drinkingcoder/FlowFormer-Official#18]
I'd like to visualize an image sequence extracted from a video, and I really need the output .flo file size to be consistent with my input image. How can I do that?
My image is (120, 180, 3).
Thank you!

**Comment by drinkingcoder** [comment]
We provide an option `keep_size' [here](https://github.com/drinkingcoder/FlowFormer-Official/blob/02891c14118aa79672af970e205a5da74c3a410c/visualize_flow.py#L190). You can enable it for visualization.

**Comment by youyoubud** [comment]
I have tried this, but it  didn't work.
`computing flow...
Traceback (most recent call last):
  File "visualize_flow.py", line 213, in <module>
    visualize_flow(root_dir, viz_root_dir, model, img_pairs, args.keep_size)
  File "visualize_flow.py", line 157, in visualize_flow
    flow, weights = compute_flow(model, image1, image2, weights)
  File "visualize_flow.py", line 76, in compute_flow
    weights = compute_weight(hws, image_size, sigma=0.05)
  File "visualize_flow.py", line 61, in compute_weight
    weights[:, idx, h:h+patch_size[0], w:w+patch_size[1]] = weights_hw
RuntimeError: The expanded size of the tensor (180) must match the existing size (960) at non-singleton dimension 2.  Target sizes: [1, 120, 180].  Tensor sizes: [432, 960]
`
Did I do something wrong?
Thank you again!

**Comment by drinkingcoder** [comment]
I updated the visualize_flow.py. You can try again.

**Comment by youyoubud** [comment]
It works, thank you!
