### ISSUE TITLE
What is self.layers in MemoryEnoder?

### ISSUE THREAD

**Issue by qinliuliuqin** [drinkingcoder/FlowFormer-Official#23]
Thanks for the great work!
I am reading your code and am confused by this [line](https://github.com/drinkingcoder/FlowFormer-Official/blob/21be9d720b24310d1e739d044e812034ab875b33/core/FlowFormer/LatentCostFormer/encoder.py#L359). It seems self.cfg.feat_cross_attn is always set to False, right?

Best,
Qin

**Comment by drinkingcoder** [comment]
Yes. We tried to exchange information between two images via cross-attention but found that it doesn't work so we permanently disabled this option.

**Comment by qinliuliuqin** [comment]
I see. Thanks for your confirmation.
