### ISSUE TITLE
About evaluate_FlowFormer_tile

### ISSUE THREAD

**Issue by xiewende** [drinkingcoder/FlowFormer-Official#24]
When i adopted validate_kitti to validate Kitti training set basd on model trainged in C+T, what is the meaning of the TRAIN_SIZE = [376, 720]? While the traing size is [432, 960] in configs/thing.py.
In addition, I directly used validate_kitti in evaluate_FlowFormer_tile to validate my own model and got very poor results.
Did I miss some details.

**Comment by drinkingcoder** [comment]
1.  TRAIN_SIZE denotes the size of the tile. The image height in KITTI is 374~376, so we directly use 376 and adjust the corresponding image width.
2. Please note that we have updated our configs: add_noise=True. We find that color_jitter is meaningless for the Sintel benchmark but essential for the KITTI benchmark.
