### ISSUE TITLE
CUDA out of memory when run "python visualize_flow.py --eval_type seq"

### ISSUE THREAD

**Issue by andersonhusky** [drinkingcoder/FlowFormer-Official#25]
Thanks for your excellent work! I use the command "python visualize_flow.py --eval_type seq" to test the code, and got an error "RuntimeError: CUDA out of memory. Tried to allocate 1.48 GiB (GPU 0; 5.78 GiB total capacity; 2.33 GiB already allocated; 1008.06 MiB free; 2.99 GiB reserved in total by PyTorch)"
My gpu is 3060 with 6GB memory, I dont understand why "out of memory" during inference?

**Comment by qjin7796** [comment]
Same problem even with few low res frames

**Comment by qjin7796** [comment]
> 

You can reduce the TRAIN_SIZE parameter in visualize_flow.py

**Comment by drinkingcoder** [comment]
Yes. You can reduce the TRAIN_SIZE. You can also try the FlowFormer-small. :hugs:
