### ISSUE TITLE
Question about the result on Sintel benchmark

### ISSUE THREAD

**Issue by MiaoJieF** [drinkingcoder/FlowFormer-Official#26]
May I ask whether the results on sintel in the paper do not use the 'warm start' policy? If so, have you tested the results of using the 'warm start' policy?

**Comment by drinkingcoder** [comment]
We don't use 'warm start' because we find that 'warm start' didn't help FlowFormer.

**Comment by MiaoJieF** [comment]
> 

I have another puzzle. Why are the results in your paper slightly different from the results on the Sintel website?

**Comment by MiaoJieF** [comment]
Have you updated the model parameters? The result I test on Sintel with ‘things.pth’ without tile is 1.00 and 2.36. Slightly better than 1.01 and 2.40 in the paper.

**Comment by drinkingcoder** [comment]
We find that the model tested in different environments present slightly different performances. We reproduce your results on a 1080Ti machine but the numbers are 1.01 and 2.40 on a V100 machine.
