### ISSUE TITLE
How to find the model information

### ISSUE THREAD

**Issue by Lerbish** [drinkingcoder/FlowFormer-Official#28]
Thanks for your algorithm.

Is there a way to look into the model? I'm quite confused how to find the convolution functions in the code.

**Comment by drinkingcoder** [comment]
Do you mean the convs for patch embedding? It's [here](https://github.com/drinkingcoder/FlowFormer-Official/blob/21be9d720b24310d1e739d044e812034ab875b33/core/FlowFormer/LatentCostFormer/encoder.py#L32). The model's structures are inside the `core/FlowFormer`.

**Comment by Lerbish** [comment]
Thanks so far.
But it's more of a general problem of understanding what happens if you - for example - call module(image1, image2)

**Comment by drinkingcoder** [comment]
Maybe [this](https://github.com/drinkingcoder/FlowFormer-Official/blob/21be9d720b24310d1e739d044e812034ab875b33/train_FlowFormer.py#L89) is the code entry you are looking for?
