### ISSUE TITLE
Occur error when running model sintel.pth

### ISSUE THREAD

**Issue by SparkElf** [drinkingcoder/FlowFormer-Official#33]
![image](https://user-images.githubusercontent.com/58362707/221121933-c262d40a-a05e-4fa4-b5f8-136824173fa0.png)
Hello, I meet an problem when running model stintel.pth,this is hard to solve for me,could you help me?

**Comment by drinkingcoder** [comment]
Did you modify the config file? It seems that the checkpoint you load to FlowFormer doesn't contain the feat_encoder module?
