### ISSUE TITLE
Is it possible to provide inference code?

### ISSUE THREAD

**Issue by WangTaoAs** [drinkingcoder/FlowFormer-Official#5]
Thanks for your great work!
I want to visualize some videos, Is it possible to provide inference code?

**Comment by drinkingcoder** [comment]
We will add this requirement into our schedule. For now, you can refer to this [code snippet](https://github.com/drinkingcoder/FlowFormer-Official/blob/3b1edc7b8e050926a609bec1ae773371c3a33a3a/evaluate_FlowFormer_tile.py#L185) for visualization.

**Comment by drinkingcoder** [comment]
The inference code and flow visualization code have been updated. Please check it :nerd_face:. You can extract an image sequence from the video and follow the guideline for visualization.
