### ISSUE TITLE
question about how to estimate high resolution image

### ISSUE THREAD

**Issue by KouseiHongqing** [drinkingcoder/FlowFormer-Official#6]
thanks for your works,
the number of parameters is about 16000000, it is impossible to estimate higher resolution image(2k or higher) in cuda.
Do you have a lighter model to solve it?

**Comment by drinkingcoder** [comment]
We will provide a lighter model afterward, but we don't recommend using FlowFormer in high-resolution images because FlowFormer is relatively sensitive to image size.

**Comment by drinkingcoder** [comment]
A small version of FlowFormer has been provided :partying_face:. Please check it and refer to README.
