### ISSUE TITLE
question about feat_encoder

### ISSUE THREAD

**Issue by mansang127** [drinkingcoder/FlowFormer-Official#7]
The code extracts the features of img1 and img2 respectively, while in RAFT, the features of two images are extracted at the same time by concat, is there a difference in effect?

Code snippets (RAFT) :
fmap1, fmap2 = self.fnet([image1, image2])      

Code snippets (FlowFormer) :
feat_s = self.feat_encoder(img1)
feat_t = self.feat_encoder(img2)

It seems that both are weight-sharing, but will running the extractor twice be slower?

**Comment by drinkingcoder** [comment]
Thanks for such a detailed code check. The image pair in RAFT are concatenated along the batch dimension, which makes the two inferences combined in a single inference. After testing, we find that inference with concatenation costs around 0.0052s while separated inference costs around 0.0085s :dizzy_face:. However, the computation is exactly the same and the time reduction is minor compared to the whole inference time. Thanks for pointing that out. We will update the code.

**Comment by mansang127** [comment]
Thanks for the prompt and patient response!

**Comment by mansang127** [comment]
> Thanks for such a detailed code check. The image pair in RAFT are concatenated along the batch dimension, which makes the two inferences combined in a single inference. After testing, we find that inference with concatenation costs around 0.0052s while separated inference costs around 0.0085s 😵. However, the computation is exactly the same and the time reduction is minor compared to the whole inference time. Thanks for pointing that out. We will update the code.

Thanks for the prompt and patient response!

**Comment by drinkingcoder** [comment]
The code has been updated~
