### ISSUE TITLE
Using the code without GPU

### ISSUE THREAD

**Issue by Shibrel** [drinkingcoder/FlowFormer-Official#9]
I want to use the Flowformer on a system without GPU but the code uses CUDA. Can someone explain what I have to change to run the train.sh?

**Comment by drinkingcoder** [comment]
Thanks for your attention, but I believe our code is unsuitable for running without GPU :thinking:.

**Comment by Shibrel** [comment]
Oh that's a bummer. I guessed it was because on the KITTI 2015 benchmark FlowFormer is listed with CPU 2,5GHz usage.

**Comment by drinkingcoder** [comment]
Sorry for the mistake :face_with_head_bandage:. The information on KITTI has been updated
